export interface Country {
  name: string;
  isoCode: string;
  phoneCode: string;
}

export const allCountries: Country[] = [
    { name: 'Afghanistan', isoCode: 'AF', phoneCode: '+93' },
    { name: 'Albania', isoCode: 'AL', phoneCode: '+355' },
    { name: 'Algeria', isoCode: 'DZ', phoneCode: '+213' },
    { name: 'Andorra', isoCode: 'AD', phoneCode: '+376' },
    { name: 'Angola', isoCode: 'AO', phoneCode: '+244' },
    { name: 'Argentina', isoCode: 'AR', phoneCode: '+54' },
    { name: 'Armenia', isoCode: 'AM', phoneCode: '+374' },
    { name: 'Australia', isoCode: 'AU', phoneCode: '+61' },
    { name: 'Austria', isoCode: 'AT', phoneCode: '+43' },
    { name: 'Azerbaijan', isoCode: 'AZ', phoneCode: '+994' },
    { name: 'Bahamas', isoCode: 'BS', phoneCode: '+1-242' },
    { name: 'Bahrain', isoCode: 'BH', phoneCode: '+973' },
    { name: 'Bangladesh', isoCode: 'BD', phoneCode: '+880' },
    { name: 'Belarus', isoCode: 'BY', phoneCode: '+375' },
    { name: 'Belgium', isoCode: 'BE', phoneCode: '+32' },
    { name: 'Belize', isoCode: 'BZ', phoneCode: '+501' },
    { name: 'Benin', isoCode: 'BJ', phoneCode: '+229' },
    { name: 'Bhutan', isoCode: 'BT', phoneCode: '+975' },
    { name: 'Bolivia', isoCode: 'BO', phoneCode: '+591' },
    { name: 'Bosnia and Herzegovina', isoCode: 'BA', phoneCode: '+387' },
    { name: 'Botswana', isoCode: 'BW', phoneCode: '+267' },
    { name: 'Brazil', isoCode: 'BR', phoneCode: '+55' },
    { name: 'Brunei', isoCode: 'BN', phoneCode: '+673' },
    { name: 'Bulgaria', isoCode: 'BG', phoneCode: '+359' },
    { name: 'Burkina Faso', isoCode: 'BF', phoneCode: '+226' },
    { name: 'Cambodia', isoCode: 'KH', phoneCode: '+855' },
    { name: 'Cameroon', isoCode: 'CM', phoneCode: '+237' },
    { name: 'Canada', isoCode: 'CA', phoneCode: '+1' },
    { name: 'Central African Republic', isoCode: 'CF', phoneCode: '+236' },
    { name: 'Chad', isoCode: 'TD', phoneCode: '+235' },
    { name: 'Chile', isoCode: 'CL', phoneCode: '+56' },
    { name: 'China', isoCode: 'CN', phoneCode: '+86' },
    { name: 'Colombia', isoCode: 'CO', phoneCode: '+57' },
    { name: 'Congo', isoCode: 'CG', phoneCode: '+242' },
    { name: 'Costa Rica', isoCode: 'CR', phoneCode: '+506' },
    { name: 'Croatia', isoCode: 'HR', phoneCode: '+385' },
    { name: 'Cuba', isoCode: 'CU', phoneCode: '+53' },
    { name: 'Cyprus', isoCode: 'CY', phoneCode: '+357' },
    { name: 'Czech Republic', isoCode: 'CZ', phoneCode: '+420' },
    { name: 'Denmark', isoCode: 'DK', phoneCode: '+45' },
    { name: 'Djibouti', isoCode: 'DJ', phoneCode: '+253' },
    { name: 'Dominican Republic', isoCode: 'DO', phoneCode: '+1-809' },
    { name: 'Ecuador', isoCode: 'EC', phoneCode: '+593' },
    { name: 'Egypt', isoCode: 'EG', phoneCode: '+20' },
    { name: 'El Salvador', isoCode: 'SV', phoneCode: '+503' },
    { name: 'Estonia', isoCode: 'EE', phoneCode: '+372' },
    { name: 'Ethiopia', isoCode: 'ET', phoneCode: '+251' },
    { name: 'Fiji', isoCode: 'FJ', phoneCode: '+679' },
    { name: 'Finland', isoCode: 'FI', phoneCode: '+358' },
    { name: 'France', isoCode: 'FR', phoneCode: '+33' },
    { name: 'Gabon', isoCode: 'GA', phoneCode: '+241' },
    { name: 'Georgia', isoCode: 'GE', phoneCode: '+995' },
    { name: 'Germany', isoCode: 'DE', phoneCode: '+49' },
    { name: 'Ghana', isoCode: 'GH', phoneCode: '+233' },
    { name: 'Greece', isoCode: 'GR', phoneCode: '+30' },
    { name: 'Guatemala', isoCode: 'GT', phoneCode: '+502' },
    { name: 'Honduras', isoCode: 'HN', phoneCode: '+504' },
    { name: 'Hungary', isoCode: 'HU', phoneCode: '+36' },
    { name: 'Iceland', isoCode: 'IS', phoneCode: '+354' },
    { name: 'India', isoCode: 'IN', phoneCode: '+91' },
    { name: 'Indonesia', isoCode: 'ID', phoneCode: '+62' },
    { name: 'Iran', isoCode: 'IR', phoneCode: '+98' },
    { name: 'Iraq', isoCode: 'IQ', phoneCode: '+964' },
    { name: 'Ireland', isoCode: 'IE', phoneCode: '+353' },
    { name: 'Israel', isoCode: 'IL', phoneCode: '+972' },
    { name: 'Italy', isoCode: 'IT', phoneCode: '+39' },
    { name: 'Jamaica', isoCode: 'JM', phoneCode: '+1-876' },
    { name: 'Japan', isoCode: 'JP', phoneCode: '+81' },
    { name: 'Jordan', isoCode: 'JO', phoneCode: '+962' },
    { name: 'Kazakhstan', isoCode: 'KZ', phoneCode: '+7' },
    { name: 'Kenya', isoCode: 'KE', phoneCode: '+254' },
    { name: 'Kuwait', isoCode: 'KW', phoneCode: '+965' },
    { name: 'Latvia', isoCode: 'LV', phoneCode: '+371' },
    { name: 'Lebanon', isoCode: 'LB', phoneCode: '+961' },
    { name: 'Liberia', isoCode: 'LR', phoneCode: '+231' },
    { name: 'Libya', isoCode: 'LY', phoneCode: '+218' },
    { name: 'Lithuania', isoCode: 'LT', phoneCode: '+370' },
    { name: 'Luxembourg', isoCode: 'LU', phoneCode: '+352' },
    { name: 'Madagascar', isoCode: 'MG', phoneCode: '+261' },
    { name: 'Malaysia', isoCode: 'MY', phoneCode: '+60' },
    { name: 'Maldives', isoCode: 'MV', phoneCode: '+960' },
    { name: 'Mali', isoCode: 'ML', phoneCode: '+223' },
    { name: 'Malta', isoCode: 'MT', phoneCode: '+356' },
    { name: 'Mexico', isoCode: 'MX', phoneCode: '+52' },
    { name: 'Monaco', isoCode: 'MC', phoneCode: '+377' },
    { name: 'Mongolia', isoCode: 'MN', phoneCode: '+976' },
    { name: 'Montenegro', isoCode: 'ME', phoneCode: '+382' },
    { name: 'Morocco', isoCode: 'MA', phoneCode: '+212' },
    { name: 'Mozambique', isoCode: 'MZ', phoneCode: '+258' },
    { name: 'Myanmar', isoCode: 'MM', phoneCode: '+95' },
    { name: 'Namibia', isoCode: 'NA', phoneCode: '+264' },
    { name: 'Nepal', isoCode: 'NP', phoneCode: '+977' },
    { name: 'Netherlands', isoCode: 'NL', phoneCode: '+31' },
    { name: 'New Zealand', isoCode: 'NZ', phoneCode: '+64' },
    { name: 'Nicaragua', isoCode: 'NI', phoneCode: '+505' },
    { name: 'Niger', isoCode: 'NE', phoneCode: '+227' },
    { name: 'Nigeria', isoCode: 'NG', phoneCode: '+234' },
    { name: 'North Korea', isoCode: 'KP', phoneCode: '+850' },
    { name: 'North Macedonia', isoCode: 'MK', phoneCode: '+389' },
    { name: 'Norway', isoCode: 'NO', phoneCode: '+47' },
    { name: 'Oman', isoCode: 'OM', phoneCode: '+968' },
    { name: 'Pakistan', isoCode: 'PK', phoneCode: '+92' },
    { name: 'Panama', isoCode: 'PA', phoneCode: '+507' },
    { name: 'Paraguay', isoCode: 'PY', phoneCode: '+595' },
    { name: 'Peru', isoCode: 'PE', phoneCode: '+51' },
    { name: 'Philippines', isoCode: 'PH', phoneCode: '+63' },
    { name: 'Poland', isoCode: 'PL', phoneCode: '+48' },
    { name: 'Portugal', isoCode: 'PT', phoneCode: '+351' },
    { name: 'Qatar', isoCode: 'QA', phoneCode: '+974' },
    { name: 'Romania', isoCode: 'RO', phoneCode: '+40' },
    { name: 'Russia', isoCode: 'RU', phoneCode: '+7' },
    { name: 'Saudi Arabia', isoCode: 'SA', phoneCode: '+966' },
    { name: 'Senegal', isoCode: 'SN', phoneCode: '+221' },
    { name: 'Serbia', isoCode: 'RS', phoneCode: '+381' },
    { name: 'Singapore', isoCode: 'SG', phoneCode: '+65' },
    { name: 'Slovakia', isoCode: 'SK', phoneCode: '+421' },
    { name: 'Slovenia', isoCode: 'SI', phoneCode: '+386' },
    { name: 'Somalia', isoCode: 'SO', phoneCode: '+252' },
    { name: 'South Africa', isoCode: 'ZA', phoneCode: '+27' },
    { name: 'South Korea', isoCode: 'KR', phoneCode: '+82' },
    { name: 'Spain', isoCode: 'ES', phoneCode: '+34' },
    { name: 'Sri Lanka', isoCode: 'LK', phoneCode: '+94' },
    { name: 'Sudan', isoCode: 'SD', phoneCode: '+249' },
    { name: 'Sweden', isoCode: 'SE', phoneCode: '+46' },
    { name: 'Switzerland', isoCode: 'CH', phoneCode: '+41' },
    { name: 'Syria', isoCode: 'SY', phoneCode: '+963' },
    { name: 'Taiwan', isoCode: 'TW', phoneCode: '+886' },
    { name: 'Tanzania', isoCode: 'TZ', phoneCode: '+255' },
    { name: 'Thailand', isoCode: 'TH', phoneCode: '+66' },
    { name: 'Togo', isoCode: 'TG', phoneCode: '+228' },
    { name: 'Tunisia', isoCode: 'TN', phoneCode: '+216' },
    { name: 'Turkey', isoCode: 'TR', phoneCode: '+90' },
    { name: 'Uganda', isoCode: 'UG', phoneCode: '+256' },
    { name: 'Ukraine', isoCode: 'UA', phoneCode: '+380' },
    { name: 'United Arab Emirates', isoCode: 'AE', phoneCode: '+971' },
    { name: 'United Kingdom', isoCode: 'GB', phoneCode: '+44' },
    { name: 'United States', isoCode: 'US', phoneCode: '+1' },
    { name: 'Uruguay', isoCode: 'UY', phoneCode: '+598' },
    { name: 'Uzbekistan', isoCode: 'UZ', phoneCode: '+998' },
    { name: 'Venezuela', isoCode: 'VE', phoneCode: '+58' },
    { name: 'Vietnam', isoCode: 'VN', phoneCode: '+84' },
    { name: 'Yemen', isoCode: 'YE', phoneCode: '+967' },
    { name: 'Zambia', isoCode: 'ZM', phoneCode: '+260' },
    { name: 'Zimbabwe', isoCode: 'ZW', phoneCode: '+263' },
];

export const popularCountries: Country[] = [
    { name: 'India', isoCode: 'IN', phoneCode: '+91' },
    { name: 'United States', isoCode: 'US', phoneCode: '+1' },
    { name: 'United Kingdom', isoCode: 'GB', phoneCode: '+44' },
    { name: 'Canada', isoCode: 'CA', phoneCode: '+1' },
    { name: 'Australia', isoCode: 'AU', phoneCode: '+61' },
    { name: 'Germany', isoCode: 'DE', phoneCode: '+49' },
    { name: 'France', isoCode: 'FR', phoneCode: '+33' },
    { name: 'United Arab Emirates', isoCode: 'AE', phoneCode: '+971' },
    { name: 'Singapore', isoCode: 'SG', phoneCode: '+65' },
    { name: 'China', isoCode: 'CN', phoneCode: '+86' },
    { name: 'Japan', isoCode: 'JP', phoneCode: '+81' },
    { name: 'South Africa', isoCode: 'ZA', phoneCode: '+27' },
];